### ISSUE TITLE
Use tags for rancher-cli version

### ISSUE THREAD

**Issue by spawnia** [monostream/docker-rancher-cli#1]
Nice image, very minimal and well done!

It would be handy to use tags, corresponding to the used version of rancher-cli. That way, you are able to specify the version of rancher-cli you want when pulling the image.

View my fork for how i used the tagging scheme.

**Comment by dominikhahn** [comment]
Hi @spawnia
Feel free to create a PR

**Comment by spawnia** [comment]
Thanks for the reply, i tried to do this. Unfortunately, tags can not be set via pull requests.

I managed to set up autobuild to my own dockerhub and version the images via tags in my fork, i was thinking that could be a nice feature to have on your main repo.

**Comment by dominikhahn** [comment]
@spawnia done, see https://github.com/monostream/docker-rancher-cli/commit/3dc543bba38f1aae421f158ec7ed7b8abc5b96c5
